name: Generate and Update GitHub Contributions Snake

on:
  schedule:
    - cron: "*/30 * * * *" 
  workflow_dispatch: 

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Generate Contribution Snake GIF
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AdiInfiniteLoop
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Update README
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'AdiInfiniteLoop'
          author_email: 'actions@github.com'
          message: 'Update contribution snake in README'
          add: 'dist/github-contribution-grid-snake.svg'
          committer_name: 'GitHub Actions'
          committer_email: 'actions@github.com'
        
      - name: Update README with Snake Image
        run: |
          # Assuming the image is in dist/github-contribution-grid-snake.svg
          echo "![Contribution Snake](dist/github-contribution-grid-snake.svg)" >> README.md
          git add README.md
          git commit -m "Update README with new contribution snake"
          git push
